export const BADGE_DEFINITIONS = [
  {
    id: 'first_recommendation',
    name: '初出茅庐',
    description: '首次完成一个推荐学习资源',
    icon: '🌱',
    category: '学习',
    rarity: 'common',
    color: '#22c55e',
    bgColor: '#dcfce7',
    target: 1,
    type: 'completed_resources',
  },
  {
    id: 'recommendation_10',
    name: '勤学苦练',
    description: '累计完成10个推荐学习资源',
    icon: '📚',
    category: '学习',
    rarity: 'uncommon',
    color: '#3b82f6',
    bgColor: '#dbeafe',
    target: 10,
    type: 'completed_resources',
  },
  {
    id: 'recommendation_50',
    name: '博览群书',
    description: '累计完成50个推荐学习资源',
    icon: '🎓',
    category: '学习',
    rarity: 'rare',
    color: '#8b5cf6',
    bgColor: '#ede9fe',
    target: 50,
    type: 'completed_resources',
  },
  {
    id: 'streak_3',
    name: '小试牛刀',
    description: '连续3天学习打卡',
    icon: '🔥',
    category: '打卡',
    rarity: 'common',
    color: '#f97316',
    bgColor: '#ffedd5',
    target: 3,
    type: 'streak_days',
  },
  {
    id: 'streak_7',
    name: '坚持不懈',
    description: '连续7天学习打卡',
    icon: '⭐',
    category: '打卡',
    rarity: 'uncommon',
    color: '#f59e0b',
    bgColor: '#fef3c7',
    target: 7,
    type: 'streak_days',
  },
  {
    id: 'streak_30',
    name: '持之以恒',
    description: '连续30天学习打卡',
    icon: '🏆',
    category: '打卡',
    rarity: 'legendary',
    color: '#ef4444',
    bgColor: '#fee2e2',
    target: 30,
    type: 'streak_days',
  },
  {
    id: 'wrong_zero',
    name: '错题清零',
    description: '将所有错题全部订正完成',
    icon: '✅',
    category: '错题',
    rarity: 'uncommon',
    color: '#10b981',
    bgColor: '#d1fae5',
    target: 1,
    type: 'wrong_zero',
  },
  {
    id: 'wrong_correct_10',
    name: '纠错达人',
    description: '累计订正10道错题',
    icon: '💡',
    category: '错题',
    rarity: 'common',
    color: '#06b6d4',
    bgColor: '#cffafe',
    target: 10,
    type: 'corrected_wrong',
  },
  {
    id: 'wrong_correct_50',
    name: '精益求精',
    description: '累计订正50道错题',
    icon: '🔧',
    category: '错题',
    rarity: 'rare',
    color: '#14b8a6',
    bgColor: '#ccfbf1',
    target: 50,
    type: 'corrected_wrong',
  },
  {
    id: 'favorite_5',
    name: '收藏新秀',
    description: '收藏5个学习资源',
    icon: '💛',
    category: '收藏',
    rarity: 'common',
    color: '#eab308',
    bgColor: '#fef9c3',
    target: 5,
    type: 'favorites',
  },
  {
    id: 'favorite_20',
    name: '收藏达人',
    description: '收藏20个学习资源',
    icon: '💎',
    category: '收藏',
    rarity: 'uncommon',
    color: '#ec4899',
    bgColor: '#fce7f3',
    target: 20,
    type: 'favorites',
  },
  {
    id: 'favorite_50',
    name: '收藏大师',
    description: '收藏50个学习资源',
    icon: '👑',
    category: '收藏',
    rarity: 'rare',
    color: '#d946ef',
    bgColor: '#fae8ff',
    target: 50,
    type: 'favorites',
  },
  {
    id: 'pomodoro_5',
    name: '番茄入门',
    description: '完成5个番茄钟',
    icon: '🍅',
    category: '专注',
    rarity: 'common',
    color: '#ef4444',
    bgColor: '#fee2e2',
    target: 5,
    type: 'pomodoro_count',
  },
  {
    id: 'pomodoro_30',
    name: '专注达人',
    description: '完成30个番茄钟',
    icon: '⏰',
    category: '专注',
    rarity: 'uncommon',
    color: '#dc2626',
    bgColor: '#fecaca',
    target: 30,
    type: 'pomodoro_count',
  },
  {
    id: 'pomodoro_100',
    name: '时间管理大师',
    description: '完成100个番茄钟',
    icon: '🎯',
    category: '专注',
    rarity: 'legendary',
    color: '#b91c1c',
    bgColor: '#fca5a5',
    target: 100,
    type: 'pomodoro_count',
  },
  {
    id: 'study_hour_10',
    name: '初学乍练',
    description: '累计学习时长达10小时',
    icon: '📖',
    category: '学习',
    rarity: 'common',
    color: '#6366f1',
    bgColor: '#e0e7ff',
    target: 600,
    type: 'study_minutes',
  },
  {
    id: 'study_hour_50',
    name: '勤学不辍',
    description: '累计学习时长达50小时',
    icon: '📝',
    category: '学习',
    rarity: 'rare',
    color: '#4f46e5',
    bgColor: '#c7d2fe',
    target: 3000,
    type: 'study_minutes',
  },
  {
    id: 'flashcard_20',
    name: '闪卡新手',
    description: '完成20次闪卡复习',
    icon: '🃏',
    category: '闪卡',
    rarity: 'common',
    color: '#0ea5e9',
    bgColor: '#e0f2fe',
    target: 20,
    type: 'flashcard_reviews',
  },
  {
    id: 'flashcard_100',
    name: '记忆高手',
    description: '完成100次闪卡复习',
    icon: '🧠',
    category: '闪卡',
    rarity: 'rare',
    color: '#0284c7',
    bgColor: '#bae6fd',
    target: 100,
    type: 'flashcard_reviews',
  },
]

export const RARITY_LABELS = {
  common: '普通',
  uncommon: '稀有',
  rare: '珍贵',
  legendary: '传说',
}

export const RARITY_ORDER = ['common', 'uncommon', 'rare', 'legendary']
